### PR TITLE
Remove insecure printStackTrace calls.

### LINKED ISSUE #96: Remove insecure printStackTrace calls.
**Describe the bug**
There are several printStackTrace calls in the code.  Throwable.printStackTrace(...) prints a Throwable and its stack trace to System.Err (by default) which is not easily parseable and can expose sensitive information.

**To Reproduce**
You can see in the code that these problems exist.

**Expected behavior**
Instead of printstacktrace, use a logger to show the message.

### PR DESCRIPTION
**Pull request by wjonassen**
## Problem Description
There are several calls to throwable.printStackTrace throughout the rest-api project.  These have been flagged as insecure and need to be removed.
Fixes #96. 
Throwable.printStackTrace(...) prints a Throwable and its stack trace to System.Err (by default) which is not easily parseable and can expose sensitive information.

## Solution
Use a logger to get the same message to the user.

## how you tested the change
Forced one of these conditions and verified the logger logged the message.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

### CODE REVIEW

File: opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/AppResources.java [hunk 1]
```diff
@@ -308,9 +309,9 @@ public void procFinished(String procName, Object obj, int exitStatus)
 		}
 		catch (IOException ex)
 		{
-			ex.printStackTrace();
-			throw new WebAppException(ErrorCodes.DATABASE_ERROR,
-				"Error attempting to start appId=" + appId + ": " + ex);
+			Logger.getLogger(ApiConstants.loggerName).log(Level.WARNING,
```
Comment (adamkorynta) [inline opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/AppResources.java:312]: Add the exception to the WebAppException overload and remove the redundant log message

File: opendcs-rest-api/src/main/java/org/opendcs/odcsapi/lrgsclient/ApiLddsClient.java [hunk 2]
```diff
@@ -656,17 +651,17 @@ public void setStrongOnly(boolean strongOnly)
 
 	public void info(String str)
 	{
-		Logger.getLogger(ApiConstants.loggerName).info("LddsClient INFO: " + str);
+		LoggerFactory.getLogger(ApiConstants.loggerName).info("LddsClient INFO: {}", str);
```
[the remark this answers is not in the document]
Comment (adamkorynta) [reply opendcs-rest-api/src/main/java/org/opendcs/odcsapi/lrgsclient/ApiLddsClient.java:654]: also it should be initialized as a constant in the class
`private static final LoggerFactory LOGGER = LoggerFactory.getLogger(ApiLddsClient.getClass());`

File: opendcs-rest-api/src/main/java/org/opendcs/odcsapi/util/ApiBasicClient.java [hunk 3]
```diff
@@ -143,30 +145,27 @@ public void disconnect( )
...
 			{
 				if (socket != null)
 					socket.close();
 			}
-			catch (Exception e)
+			catch (IOException ex)
 			{
-				System.out.println("Error closing socket: "+e.getMessage());
-				e.printStackTrace();
+				throw new IOException( "Error closing socket: ", ex);
```
Comment (adamkorynta) [inline opendcs-rest-api/src/main/java/org/opendcs/odcsapi/util/ApiBasicClient.java:168]: This doesn't add much context, I'd just remove the catch since it's throwing the same exception anyways

File: opendcs-rest-api/src/main/java/org/opendcs/odcsapi/util/ApiBasicClient.java [hunk 4]
```diff
@@ -143,30 +145,27 @@ public void disconnect( )
...
+            try
 			{
-				if (output != null)
-					output.close();
-			}
-			catch (Exception e)
+                if (output != null)
+                    output.close();
+            }
+			catch (IOException ex)
```
Comment (adamkorynta) [inline opendcs-rest-api/src/main/java/org/opendcs/odcsapi/util/ApiBasicClient.java:157]: I think we still want to close the socket even if the output.close() fails

Comment (wjonassen) [reply opendcs-rest-api/src/main/java/org/opendcs/odcsapi/util/ApiBasicClient.java]: I did update this in the new commit, the new code is much more readable, but technically if one close fails, the others won't be run.

Readability wise, it might make sense to do it this way?

**Review by adamkorynta — APPROVED** [review]

**Review by MikeNeilson — APPROVED** [review]
